# Generated by Django 3.0.4 on 2020-03-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(db_index=True, max_length=300, verbose_name='Task')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is completed ?')),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
