# Generated by Django 3.0.4 on 2020-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Task'),
        ),
    ]
